### ISSUE TITLE
Contract Spending Transaction (התקשרות) item shows as a Tender Exemption Notice (הודעת פטור)

### ISSUE THREAD

**Issue by akariv** [OpenBudget/open-budget-search-api#10]

**Comment by YontiLevin** [comment]
בוא נעבור על זה שבוע הבא כי נראה לי שאני לא מבין מספיק את ההבדל
פשוט ראיתי שהיו שם פטורים אז הכנסתי אותם

**Comment by akariv** [comment]
contract-spending = התקשרות רכש
One government body paying for a service with a specific purchase order

exemption = פטור ממכרז
Notice to the public that someone wants to purchase a service and bypass the tender process.

Different things (but in the same domain)

**Comment by YontiLevin** [comment]
ok
i didnt have a template for contract spending so i used the exemption template
will add extra logic next monday

**Comment by akariv** [comment]
Moved to https://github.com/OpenBudget/budgetkey-app-search/issues/11
