### ISSUE TITLE
[Search] [Performance] Do bulk indexing of records

### ISSUE THREAD

**Issue by akariv** [OpenBudget/open-budget-search-api#11]
(instead of one-by-one)

**Comment by aryehpro** [comment]
Is this issue regarding the load method in data_source.py?
You want to have the load function work with elastic's bulk api?

**Comment by OriHoch** [comment]
@aryehpro - have a look at this PR if you want to see how I did it :) 
#13

**Comment by OriHoch** [comment]
I also duplicated this load data functionality to the pipelines in this PR: https://github.com/OpenBudget/budgetkey-data-pipelines/pull/80

I guess this issue is irelevant if we use the pipelines for that..
