### ISSUE TITLE
[Search] Add kibana over elasticsearch

### ISSUE THREAD

**Issue by prsnca** [OpenBudget/open-budget-search-api#12]
In order to be able to play over elasticsearch 
https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04#install-kibana

**Comment by OriHoch** [comment]
I can do that if you give me access to all your servers muahhahaha...

**Comment by akariv** [comment]
We already have it:

http://next.obudget.org:5601/app/kibana

**Comment by prsnca** [comment]
amazing @akariv thanks!
i can haz credentials please?

**Comment by akariv** [comment]
Sure, DM me and I'll send you the creds.
