### ISSUE TITLE
search endpoint should include the doc id for each result

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/open-budget-search-api#15]
### reproduction
* be frontend app - want to show search results and link to item page
* do a request to e.g. https://next.obudget.org/search/budget,national-budget-changes,contract-spending,entities/%D7%9E%D7%99%D7%A7%D7%A8/1992-01-01/2019-01-01/10/0
* would like to link results to generic item page

#### expected
* results should have the doc id - which is needed for item page

#### actual
* no doc ids
* I can't see a way to link to item page

**Comment by akariv** [comment]
Fixed in https://github.com/OpenBudget/budgetkey-data-pipelines/pull/84

**Comment by OriHoch** [comment]
thanks, that was fast..
