### ISSUE TITLE
Expose 'sense' endpoint

### ISSUE THREAD

**Issue by ronmamo** [OpenBudget/open-budget-search-api#4]
Should allow a rapid research & development, hits the same spot of redash but for Elastic data.

ref: (old one...) https://www.elastic.co/blog/found-sense-a-cool-json-aware-interface-to-elasticsearch

- Should not be generally public: security/usability concerns need to be addressed before - if at all (such as deny deletion; deny delete all; dynamic scripting?)

**Comment by OriHoch** [comment]
it's part of Kibana now which is part of the [docker-compose stack](https://github.com/OpenBudget/open-budget-search-api/pull/13/files#diff-33063d3ae9a2d278f26de6c08a04daa2R23) (in PR #13)

> Update May 1, 2017: At the time of this writing, Sense existed purely as a Chrome plugin.  It was later made into a Kibana plugin and has now been integrated directly into Kibana as "Console" in what is known as the "Dev Tools" section

**Comment by OriHoch** [comment]
we also have a Kibana installation on production, so I think we can safely close this issue, thanks :+1:
