### ISSUE TITLE
API returning errors for supports

### ISSUE THREAD

**Issue by akariv** [OpenBudget/open-budget-search-api#6]
http://next.obudget.org/search/supports/%D7%97%D7%99%D7%A0%D7%95%D7%9A/1992-01-01/2019-01-01/20/0

Shows
`TransportError(400, 'search_phase_execution_exception', 'For input string: "1992-01-01"')`

**Comment by OriHoch** [comment]
@akariv was it fixed? could you link to the PR or commit where it was fixed?
